# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d242229f39255999841f8713ecb77bc4cf29e827f7d2a4fc97e421a7ca529f96ba98b6efdd9150a67afad9a3cac3ca07a2d6e11cdefb860f455e2acc48ba1d4

test:
  secret_key_base: cc39d921e8e75558ce2f8e7046d59cf89acba9fd4b3e55ce69d4f36efcb20efcee3d787a6f103f290c06111611f14a4293ae3b7ef7d8467957071599511124d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
